### ISSUE TITLE
Unable to Install Active Account in FTB App After Errors.

### ISSUE THREAD

**Issue by roadmaster64** [FTBTeam/FTB-App#1140]
### What Operating System

Windows 10

### Debug Code

FTB-DBGOHOBAZERIS

### Describe the bug

Hi not sure where to ask this, I think it's a Bug but not sure.

Yesterday I was playing FTB Minecraft ATM9 when I accidentally hit some keys on my keyboard, and by accidentally I have no idea what I hit, anyway GeForce pulled up a game overlay on me, I didn't remember how to shut it down.  So, I started hitting some key combinations to hopefully hit the right combination to shut it down. I couldn't get it off my screen.  So, I shut down Minecraft and FTB.  When I restarted FTB and tried to log back in I got a "Profile" Error. it sent me to Microsoft to login to my Microsoft account then sent me back to FTB where I was told (after several attempts) errors in (Profile, No Minecraft Account, and an Xbox down error). I finally shut everything down, went into _user/Appdata/anythingFTB_ and deleted everything, then I restarted my computer.

Upon restart I got online (several times during this process) and downloaded the FTB App and found that I no longer had an active account on my FTB App, now whenever I try to Add an Account it sends me to the same process of going to Microsoft to verify my account and every time Microsoft sends me back to the FTB app where at the latest I was told about an Xbox error (**FTB-AUTH-000003 _Weve been unable to communicate with Xbox Live.  It's possible their services are down._) (**Login to Minecraft**, _something has gone wrong, we can't proceed._)**  There's nothing wrong with my Microsoft account, I can log in to it in multiple ways, also there's nothing wrong with my Minecraft account as I can log in with the vanilla launcher no problem, I even downloaded **MultiMC** which allows me to create an instance of any FTB Modpack using their _New Instance/FTB App Import_ option, going this way I can login to the game just fine.

### Steps to reproduce

_I doubt anyone else can reproduce this unless they are having the exact same issue. however,_
1.  Start up FTB App
2.  Press Add Account Button lower left side of the App.
3.  Press the Microsoft button on the popup window.
4.  Press the Microsoft button on the browser window popup.
5.  Window Pops up with my E-mail already there with a line for my password, I type in my password, click the sign in button.
6.  Browser window pops up with "Your In" then immediately brings up the ftb app where i goes through several entrys befor stopping and going to the Xbox Error.
7.   Rinse and Repeat.

### Expected behaviour

I have had my Minecraft account since before Microsoft took over, had no problem switching over from Mojang to my Microsoft account.  I have been playing FTB Modpacks through the App for several years, I shouldn't have any problem adding an account as I have done it many times before.

### Additional information

I suspected that I had corrupted a file somewhere but as I already uninstalled the FTB App and Deleted the Appdata folders I found with FTB text in the folder name, I am at a loss as to where or what to do at this point.

**Comment by ThatIsFalseSir** [comment]
I am having the exact same issue. Reinstalled, restarted, cleared caches, nothing works. I do have the same issue on Curseforge as well,

**Comment by PTHunterBR** [comment]
I'm having the same issue, "FTB-AUTH-000003 We can't communicate with Xbox Live. Your services may be down.". However, I can play using vanilla and other launchers and it is only with the ftb desktop app that I have this problem. This started from yesterday to today.

**Comment by WyFryMU** [comment]
Copy paste from the ftb discord:

## Auth issues with the App

Hi all, we've noticed an increase in users having issues logging into their Minecraft accounts using the FTB App. 

From our investigation, it looks like this is an issue on Mojangs side, and we hope they will have resolved this issue soon. We have confirmed this issue is happening in other Launchers as well.... 😢

The only known work around right now is to take a break and come back to the app in an hour or so and hope that it's been long enough that Mojang will no longer think you've spammed their servers (Even though you haven't)

Sorry for any inconvenience this may have caused ❤️

### Technical stuff

It looks like users are randomly getting 429 errors on any one of the Mojang API's. From user reports, our users aren't sending loads of requests, and it's just randomly happening... Due to this being a 429 error (Which means too many requests) we don't have any real workarounds other than giving it a break and coming back to it later...

**Comment by PTHunterBR** [comment]
Apparently the problem is not with the FTB, but with the Minecraft authentication servers, today the problem started to happen with the Minecraft launcher itself or with Xbox Live, with a little research I found it on Mojang's bug report website

"There is an outage currenty going on which affects the xbox servers and in turn, the Minecraft licensing/auth servers. This means it's possible you may be unable to change your name, your skin, or be able to play Minecraft at all, regardless of your launcher. Your purchase is not at risk however and if the game shows as unowned, this should be resolved when the outage is resolved."

I don't know if there are links here, It's sad, but it looks like we'll have to wait.
https://bugs.mojang.com/browse/WEB-7179

**Comment by MichaelHillcox** [comment]
please see #1142
