### ISSUE TITLE
Unable to login to app

### ISSUE THREAD

**Issue by EsotericCaveman** [FTBTeam/FTB-App#1142]
### What Operating System

Windows 11

### Debug Code

FTB-DBGIWULIVARAJ

### Describe the bug

I was playing revelation when I decided to try a few new mod packs. When the app had trouble connecting I thought maybe a quick resolve would be to logout of the FTB app and then log back in. No matter how many times I try to restart the app it will not communicate with microsoft. 

When it fails to connect it says it's either my connection, microsoft's end or that I need to launch the game vanilla before I play modded. lol

This started 6/7/24 about mid afternoon EST
Have been playing for the past few weeks w/o issue

### Steps to reproduce

Not sure if this is reproduceable for everyone

### Expected behaviour

the app won't connect to microsoft

### Additional information

https://pste.ch/anodaburim

**Comment by EsotericCaveman** [comment]
UPDATE: Over the course of several hours I've tried everything to get logged back into the app and amazingly it happened! 

Idk if this had anything to do with the fix but I completely uninstalled everything and started fresh. After first few attempts at getting logged into the ftb app I simply launched vanilla to confirm it was good to go then while vanilla window is open I attempted to log into the ftb app and it worked and got all green checks. 

If you're having similar issue try opening minecraft launcher first, then log into FTB app

**Comment by WyFryMU** [comment]
Copy paste from the ftb discord:

## Auth issues with the App

Hi all, we've noticed an increase in users having issues logging into their Minecraft accounts using the FTB App. 

From our investigation, it looks like this is an issue on Mojangs side, and we hope they will have resolved this issue soon. We have confirmed this issue is happening in other Launchers as well.... 😢

The only known work around right now is to take a break and come back to the app in an hour or so and hope that it's been long enough that Mojang will no longer think you've spammed their servers (Even though you haven't)

Sorry for any inconvenience this may have caused ❤️

### Technical stuff

It looks like users are randomly getting 429 errors on any one of the Mojang API's. From user reports, our users aren't sending loads of requests, and it's just randomly happening... Due to this being a 429 error (Which means too many requests) we don't have any real workarounds other than giving it a break and coming back to it later...

**Comment by SmokedBasher673** [comment]
I'm having the same issue, keep getting "FTB-F-AUTH-000001" or some other code without the F and an ending number 1-5. I had an issue with the Minecraft launcher itself verifying that I own both Java and bedrock edition but it seems to have sorted itself out. Still can't login through the FTB app. I just wanna play Stoneblock 3 LOL. It's been an issue since yesterday for me.

**Comment by jackharrhy** [comment]
It even seems like whatever limits are set causing the 429 errors, are also affecting sessions on minecraft.net.

While visiting https://www.minecraft.net/en-us/msaprofile for example, sometimes it can't fetch profile information, so the page shows the screen logged out, or the endpoint that returns if you have a valid license for Java edition throws a 429 showing a 'Buy Now' button.

I'd hope this means this is visible on Mojang's end and fixed soon, have not been lucky and every login attempt to the FTBApp since around 11:00pm

---

It seems however that retrying... works? I can get to a state these endpoints do work after a refresh.

Maybe if the FTB App gets a 429, it could do a bit of retry logic instead of bailing quickly?

**Comment by MichaelHillcox** [comment]
Hey all, a quick update on the above, the login issue has been acknowledged by Mojang and is being actively worked on. 

You can see more here https://bugs.mojang.com/browse/WEB-7179

And 
https://x.com/mojangstatus/status/1800101837304987819

And specifically a comment from one of their team:
> There is an outage currently going on which affects the xbox servers and in turn, the Minecraft licensing/auth servers. This means it's possible you may be unable to change your name, your skin, or be able to play Minecraft at all, regardless of your launcher. Your purchase is not at risk however and if the game shows as unowned, this should be resolved when the outage is resolved.
> 
> For now keep an eye on this report as I'll do my best to update it when I get more information on the issue.

We'll be keeping a watchful eye on this situtation and keep everyone posted. It's very important to emphasise that this is effecting **ALL** launchers, including vanilla! There is nothing our team can do at this point in time.

**Comment by pbare123** [comment]
Cannot Login.  But authenticating is Success.  Please help
<img width="496" alt="Screenshot 2024-07-02 183657" src="https://github.com/FTBTeam/FTB-App/assets/55928059/350e80e3-5323-4397-ba86-ebab9d8b61c9">

**Comment by Gaz492** [comment]
> Cannot Login. But authenticating is Success. Please help <img alt="Screenshot 2024-07-02 183657" width="496" src="https://private-user-images.githubusercontent.com/55928059/345224708-350e80e3-5323-4397-ba86-ebab9d8b61c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTcwNTEsIm5iZiI6MTcyODI5Njc1MSwicGF0aCI6Ii81NTkyODA1OS8zNDUyMjQ3MDgtMzUwZTgwZTMtNTMyMy00Mzk3LWJhODYtZWJhYjlkOGI2MWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEwMjU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYTJjMjZjZTYxZjBkYTFkYjk2Y2M1YjBlZjY0MmRjOWMwMTMxZjNiODVjMjQ3NmM0MTE2MGZlMjcwMTRkYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NEOBe355gPrSKSt8L1qswj2L2D3e0PMFeygTv4_zh3w">
> <img alt="Screenshot 2024-07-02 184614" width="431" src="https://private-user-images.githubusercontent.com/55928059/345225066-368a1ea8-d15b-4965-9e20-f9ea2b25c265.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTcwNTEsIm5iZiI6MTcyODI5Njc1MSwicGF0aCI6Ii81NTkyODA1OS8zNDUyMjUwNjYtMzY4YTFlYTgtZDE1Yi00OTY1LTllMjAtZjllYTJiMjVjMjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEwMjU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NzM5MmRmMTdhMjIyZjc2NjM4YzE0ODMyYjM0NTY4NDgyNzYyZjFhMThhZjYxMmExMGMzMWViNDBkN2NkMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FjhFSUKoWa-eATrrJuXIIeVyQnmAKLIJGikJ0e5v6ec">
> 
> Copied the instance folder to Curse Forge launcher And it worked. now I can play my game.

If you are still running into this issue, could you open a new issue for us?

**Comment by Flexico** [comment]
Hang on, why did a BOT close this?
