### ISSUE TITLE
[Bug] FTBApp seems to launch with an outdated Java, which causes KubeJS to not function properly in Academy

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-App#126]
**Operating System:**
OS: Mac

**Installer Version:**
Installer: unknown

**App Version:**
App: 1.0.8

**UI Version:**
UI: unkown, I've asked the user to send it to me

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app
I've asked the user to send it to me

**Describe the bug**
FTB Academy uses KubeJS for certain things, which requires a specific version of Java or above. @LatvianModder could give a more thorough explanation since it's his mod, I don't fully understand it. When launched with the FTBApp, some users report that those things don't work. I asked the user to try MultiMC instead, and it did work for them. Their computer is using Java 8 Update 251.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch FTB Academy with FTBApp
2. Make a new world
3. Get to the iron chest upgrade quest
4. Observe as it doesn't work

**Expected behaviour**
The quest uses KubeJS to check if you've right clicked a Chest with a Wood to Iron Chest Upgrade. If you do, it's supposed to trigger a task to complete.

**Screenshots**
![image](https://user-images.githubusercontent.com/15698722/80945521-995da380-8db1-11ea-804b-c339dfd722e8.png)
![image](https://user-images.githubusercontent.com/15698722/80945550-a8dcec80-8db1-11ea-86de-53fd8e3a8018.png)

**Additional context**
This was reported by user `Agnostic.Otter#1429` on the FTB Discord, and several other people have had the same issue.
![image](https://user-images.githubusercontent.com/15698722/80945564-aed2cd80-8db1-11ea-9361-00f753119ba2.png)

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/80953920-0b3de900-8dc2-11ea-9de5-8a77c4d18d36.png)

**Comment by aaronhowser1** [comment]
https://pste.ch/epucilusih

**Comment by jamierocks** [comment]
Unless the FTB App changes the Java executable used by the launcher, this is possibly because Mojang distribute an old build of Java 8 :(

**Comment by Cloudhunter** [comment]
I'll just add my comments here - we've had an internal discussion and we should add a way to use the system installed - or other JVM. However, by default it will stay at 8 update 51, as that is what the Vanilla launcher uses.

Additionally, KubeJS should not really be relying on features above this version as that is what the official game requires. The reason it requires this is because on versions above 51, it is broken on some Intel graphics chipsets.

I'll mark this as an enhancement.

**Comment by jamierocks** [comment]
Just to clarify here, the FTB App does indeed change the JVM used by the Minecraft launcher then?

**Comment by Cloudhunter** [comment]
No, it doesn't.

**Comment by jamierocks** [comment]
I had thought so, in that case - this seems a none-issue with FTB App then, KubeJS is at fault.

However, I'm curious why you're keeping the version of Java used by the backend consistent with Mojang? (even if you're planning to use it to launch the game in the future, it still wouldn't fix the issue as its still the same Java version, for the purposes of intel hacks).

**Comment by Cloudhunter** [comment]
The backend does not use the same version that Mojang uses - we ship our own JVM.

It does seem I was a little bit mistaken regarding the Java version not being changed by us - if you have a JAVA_HOME variable set it will use that JVM - otherwise it will use Mojang's default.

We could do with another way of setting this possibly.

**Comment by Jake-E** [comment]
Closing in favour of #1 - as the only discussion left here is related to changing the JRE used.
