### ISSUE TITLE
[Bug] Startup script creation broken for some packs/mc version

### ISSUE THREAD

**Issue by jikuja** [FTBTeam/FTB-App#147]
**Operating System:**
OS: Linux

**Log Files:**
https://pste.ch/carosovale.php

**Describe the bug**
Installing FTB Infinity Evolved 1.7 v3.1.0 creates broken server scripts:
- Line three of start.sh is reverted back to old form. (Minor: does not block starting server)
- **Argument for `-jar` is missing from start.sh and start.bat**

**To Reproduce**
Steps to reproduce the behaviour:
See log.

**Expected behaviour**
Create working startup script

**Additional context**
- This was reported in Discord and was reproduciable by selecting same pack than OP selected
- Installing FTB Lite 3 1.5.0 created identical startup scripts.
- For FTB Revelations 3.2.0 name of the jar file is correctly inserted into script

Ps. ignore name of the directory I'm using.

**Comment by wangmauler** [comment]
**Operating System:**
OS: Windows 10

**No Log Files** (it hasn't even created the log folder yet)

**Describe the bug**
After installing FTB Infinity Evolved 1.7 v3.1.0 (serverinstall_23_99.exe), running "start.bat" and typing "y" for the eula results in the error below, also pictured in the link below:

"Error: unable to access jarfile nogui"
https://media.discordapp.net/attachments/560188834592063488/751233347614671018/unknown.png

**To Reproduce**
Download windows FTB Infinity Evolved Server installer
Install
run start.bat
error occurs

Expected behaviour
Normal ServerStart.bat creation behavior?

**Comment by Jake-E** [comment]
Please test with the new installer, if this is still an issue feel free to re-open.

**Comment by jikuja** [comment]
Still broken.

Tested with Vanilla+

> modpacks.ch server downloader golang - build 202120021356

```
$ ~/Downloads/serverinstall_18_117
Where would you like to install the server? [current directory]

Path . already exists - still want to install? (y/n) [y]
y
Continuing will install FTB Vanilla+ version 1.1.0. Do you wish to continue? (y/n) [y]
y
2021/02/23 07:24:07 Performing installation...
2021/02/23 07:24:07 Getting downloads for Forge Universal
2021/02/23 07:24:08 JSON not on server and unable to get forge jar: server returned 404 Not Found
```

**Comment by Cloudhunter** [comment]
Release is out

**Comment by wangmauler** [comment]
This is working no, however I get a virus infection warning - and upon submitting the exe from the FTB website to virustotal:

[https://www.feed-the-beast.com/modpack/ftb_infinity_evolved_1_7](url)

This is the result:

![infection](https://user-images.githubusercontent.com/8186826/108902656-60b1e380-75ea-11eb-92c8-0b8ba3a74367.JPG)
