### ISSUE TITLE
Dont download

### ISSUE THREAD

**Issue by borsuperman** [FTBTeam/FTB-App#167]
hi guys
i have an
issue
about ftb academy
ftb academy haves 129 mods but my launcher only downloads 29 of it
we have tryed everything
close the firewall transfer the filed
but that doesnt work
can you help us

**Comment by Sunekaer** [comment]
please fill out this information 
**Operating System:**
OS:

**Installer Version:**
Installer:

**App Version:**
App: 

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by Sunekaer** [comment]
Should be fixed now, restart the app again try installing the pack again
