### ISSUE TITLE
[Feature request] font suggestions

### ISSUE THREAD

**Issue by Sunekaer** [FTBTeam/FTB-App#187]
Font suggestions for the app
https://fonts.google.com/specimen/Mukta
https://fonts.google.com/specimen/Arimo
https://fonts.google.com/specimen/Gothic+A1

**Comment by Rushmead** [comment]
@Sunekaer Seeing as you have some development experience could you give us a screenshot of the app with each different font so that we can see what they look like?

Are you also suggesting a mixture of the fonts or simply replacing the current one with a new one?

Finally, what are your problems with the current font?

**Comment by Sunekaer** [comment]
yeah, ill do that if I can get my dev env to run :)

My issue with the current font is numbers looks weird

**Comment by Sunekaer** [comment]
Mukta
![image](https://s1.sunekaer.com/i/06-07-2020_13-37-34_ftbapp.png)

Arimo
![image](https://s1.sunekaer.com/i/06-07-2020_13-38-04_ftbapp.png)

Gothic A1
![image](https://s1.sunekaer.com/i/06-07-2020_13-38-32_ftbapp.png)

off these 3 I personally like Arimo the most
