### ISSUE TITLE
[Feature request] [Beta] Discover tab has too big a focus on videos, and shouldn't automatically play them

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-App#191]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/15698722/86527487-b6235f80-be64-11ea-80fd-c75dfadd4241.png)
Too much of this screen is dedicated to a youtube video. It's good that it defaults muted, but it shouldn't default to playing at all.

**Describe the solution you'd like**
More of the screen should be dedicated to the modpack itself, with a scrollable portion that has the modpack's longer description. The video should also probably be at the bottom instead of the top, and be smaller.

**Additional context**
![image](https://user-images.githubusercontent.com/15698722/86527512-fda9eb80-be64-11ea-8a06-cf96ecd7ab90.png)
The top of the video is covered by the blur saying who's playing it, also covering the video title and channel

**Comment by ThePaul-T** [comment]
The whole discovery system is to aid the average user who find modpacks to play by following their favourite youtubers.

The focus should and is designed to be on the video, we have pages dedicated to modpacks already and way to search via tags or click tags on existing packs.

We see evidence of the following of youtube videos to packs on very regular basis, as each time a youtuber like Dire plays a pack, we immediately get a huge surge in orders.

Just because it is not how you wish to use the feature, does not mean it is not valid - This is the deliberate design of this feature.

**Comment by Rushmead** [comment]
To further comment on this as I know people were concerned with autoplay for people with low bandwidth, we use YouTube & Twitch on these pages, which will automatically select the correct playback quality for the users bandwidth. This will use no more than as if the user was just on YouTube themself. 

If the user doesn't want the video to play, the controls are accessible and the video can be stopped.

Regarding the top bit being covered. The text that is covering the top of the video tells you the channel and what's happening in the video, which is exactly the same as what the title and the channel does in the YouTube player, I don't see a problem with this being covered.

**Comment by Cloudhunter** [comment]
Closing this as feedback given and no more responses.
