### ISSUE TITLE
[Bug] [Beta] Pack Card Size defaults to showing in List Mode, even though the slider defaults to being off

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-App#192]
**Operating System:**
OS:W10

**Installer Version:**
Installer: FTBA_windows-x64_202007042254-9878310b16-develop

![image](https://user-images.githubusercontent.com/15698722/86527550-83c63200-be65-11ea-902e-b9c525361d9d.png)

**Log Files:**
https://pste.ch/ijosoqivuh

**Describe the bug**
When you first open launcher settings, it shows Pack Card Size in list mode, even though the setting defaults to being off. When you enable list mode, it doesn't change. When you re-disable it, it goes to card mode.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to settings
2. Scroll to pack mode
3. Toggle List Mode, see how it doesn't change
4. Turn it back off, see it change

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/15698722/86527553-8b85d680-be65-11ea-97ad-9e3a5ad0dd75.png)
![image](https://user-images.githubusercontent.com/15698722/86527554-8e80c700-be65-11ea-9e29-0935589f7e15.png)
![image](https://user-images.githubusercontent.com/15698722/86527556-904a8a80-be65-11ea-9e10-5232fcb73fb2.png)

**Comment by ThePaul-T** [comment]
I've reported this a few times to @Rushmead, as well as it should auto disable list mode once size goes above 2, hopefully he can figure out what bug is causing these oddities before we go to Preview.

**Comment by Rushmead** [comment]
Seems what is happening here is that because existing installs have never had a value for listMode it is undefined if you have not visited the settings page. I attempted to fix this by adding some default values when we load the settings but this doesn't appear to have worked. I'll need to look into why the default settings aren't being applied at all times.

I haven't implemented anything that would auto-switch the list mode off after a card size of 2, but this will be simple to implement and I'll do this during my next session of bug fixes.

**Comment by Gaz492** [comment]
I believe this issue was resolved in a newer version of the app.
If you continue to experience this issue, please open a new issue.
