### ISSUE TITLE
[Bug] Linux - .desktop file does not specify is "Game", gets put in "Other" category in OS launch menu.

### ISSUE THREAD

**Issue by rallias** [FTBTeam/FTB-App#225]
**Operating System:**
OS: Debian Sid

**Installer Version:**
Installer: FTBA_unix_202007161516-479dedc615-release.sh

**App Version:**
App: 202007161516-479dedc615

**UI Version:**
UI: 39f37b8d

**Log Files:**
https://pste.ch/amimogocas

**Describe the bug**
In the .desktop file created for FTB-App, we see the following:

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Type=Application
Name=FTBApp
Exec="/home/rallias/FTBA/FTBApp" %U
Icon=/home/rallias/FTBA/.install4j/FTBApp.png
Categories=Application;
StartupWMClass=install4j-net-creeperhost-creeperlauncher-CreeperLauncher
```

In the Categories field, all that is listed is "Application". As a result, the LXDesktop launcher puts the FTBApp entry in "Other". If this was set to "Game;Application;", this would cause the FTBApp entry to be placed in the more appropriate "Games" category.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install.
2. Search desktop environment launcher for FTBApp.

**Expected behaviour**
FTBApp should be found in "Games"

**Screenshots**
![image](https://user-images.githubusercontent.com/1843506/89234404-89707e00-d5b1-11ea-81ab-95fa5cd554a1.png)

**Additional context**
\_-(o_o)-_/

**Comment by ArcticWolfSS82** [comment]
**Operating System:** Ubuntu MATE 23.04 x86_64
**App Version:** 202401041638-9dc7936164
**UI Version:** 9dc7936164
**Installer Version:** FTBA_unix_202310071959-918caed003.sh

Experiencing the same issue. Hoping someone more familiar with the code can help, as manually editing the `.desktop` file isn't a persistent fix.

From `[FTBApp-Path]/.install4j/installation.log`, I think I located the line which shows the value the "Categories" field is filled in with during installation. This is from today's update, which reverted my manual edits.
```
[...]
[INFO] com.install4j.runtime.beans.actions.desktop.CreateProgramGroupAction [ID 18]: Execute action
       Property categories: Application
       Property linkDirectory: 
       Property programGroupEntryConfigs: []
       Property programGroupName: 
       Property uninstallerMenuName: FTBApp Uninstaller
       Property addDefaultLauncherLinks: true
       Property addUninstaller: false
       Property allUsers: true
       Property failForSymlinksNotCreated: false
       Property rollbackSupported: true
       Property unixMenuEntries: true
       Property unixSymlinks: true
       Variable changed: sys.programGroupName=FTBApp[class java.lang.String]
       Variable changed: sys.symlinkDir=/usr/local/bin[class java.lang.String]
       Install file: [path]/FTBA/.install4j/install4j_1fattjo-FTBApp.desktop; size: 278 bytes; exists: true
       File options set to: [fileTime: Fri Jan 05 01:11:27 EST 2024, mode: 755, overwriteMode: Always, shared: false, uninstallMode: Always, delayIfNecessary: false]
[...]
```

Closest thing that seems related I could find after a search of the code is at https://github.com/FTBTeam/FTB-App/blob/release/vue.config.js#L103

I'm not sure if this is related to the install process category or not. If it is, perhaps the parameter has a typo (**category** instead of **categories**), but that's a shot in the dark at best.

**Comment by MichaelHillcox** [comment]
This should be fixed now
