### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by vherov** [FTBTeam/FTB-App#244]
im not able to play stone block 2, when i installed it on the ftb launcher it would be fine until i click play. i would get a message at the top right of the launcher saying i need to check the configuration..

**Comment by Gaz492** [comment]
Please follow the bug report template and provide the information that is requested.

**Operating System:**
OS:

**Installer Version:**
Installer:

**App Version:**
App: 

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by Sunekaer** [comment]
Hi
This issue has been closed due to its not using the issue template.
Feel free to open a new issue using the template.
