### ISSUE TITLE
3 mods missing from 3.0.21 install[Bug]

### ISSUE THREAD

**Issue by ImaFrakkinNinja** [FTBTeam/FTB-App#281]
**Operating System:**
OS:Windows 10 Pro

**Installer Version:**
Installer: 

**App Version:**
App: why isn't the version highlight-able for copy? 202007161516-47gdedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app

**Describe the bug**
downloaded 3.0.21 version of sky factory 3 but when connecting to hosted server on creeperhost.com this error appears:
lost connection: TextComponent{text='Mod rejections [FMLMod:Botania{r1.9-341}, FMLMod:fluxnetworks{1.2.8}, FMLMod:etlunar{1.10.2-0.10.6a}]', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}.

I had to go to my twitch mod (where i downloaded sky factory 3) and copied the three missing mods from that pack to put in the folder for the ftb app launcher.  After wards was able to connect to the server.

**To Reproduce**
Remove the three mods listed: Botania, Fluxnetworks, Etlunar

**Additional context**
Just 3 mods missing from pack.

**Comment by Gaz492** [comment]
I believe that this issue has now been resolved if you continue to have an issue where the mods are missing make sure you are on the latest version of the app and if the issue persists on the latest version of the app try the preview version (can be enabled by going to settings on the app and enabling the preview option).

If the issue is still there please open a new issue.

**Comment by ImaFrakkinNinja** [comment]
thank you
