### ISSUE TITLE
[Bug] Launcher won't open

### ISSUE THREAD

**Issue by azChaz** [FTBTeam/FTB-App#296]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer:
202007161516-479dedc615
**App Version:**
App: 
Latest as of 10/12/2020
**UI Version:**
UI: 
As above.
**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

Unable to open the launcher and can't access the log files like the tutorial says. Here is the error file I found in the FTB files though.
[error.log](https://github.com/FTBTeam/FTB-App/files/5367578/error.log)

**Describe the bug**
FTB App fails in opening. Task Manager clearly shows FTBApp.exe as running but nothing happens and no windows pops up. The error log says something about a CreeperLogger error. Reinstallation of the Launcher does not seem to fix the problem. Installing the launcher into an entirely new directory does not seem to fix it either.

**Comment by azChaz** [comment]
User Elpis4 seems to have the same issue as I do, will try what has been recommended there.

**Comment by azChaz** [comment]
Update: From what previous posts seem to be saying, the problem lies in the instance.json files within the folders of the individual modpacks under .ftba. 

Removal of everything inside the instances folder allowed the launcher to launch. However, another bug arose where clicking the play button on a pack wouldn’t open the Minecraft launcher.

Deleting launcher_profiles.json in the bin folder of .ftba fixed that problem.

In general if a bug persists after reinstalling the launcher, go to C: users [Username] .ftba  and delete the entire folder.

**Comment by cha0sbuster** [comment]
\<conjecture\>
From what I can tell wrestling with it today, the app appears to be writing malformed/corrupted jsons. I opened an instance.json up and it had barely gotten through writing one section of the file, with an open brace just hanging out there. Possible the file's getting closed before the app is finished with it. This might be causing the app to enter a loop when it tries to load, attempting to load an instance it can't read any data about. This is backed up by my error.log folder, which was presenting the same few lines over and over.
\</conjecture\>

The best approach to a workaround for now, since it appears someone's on the case, seems to be to just grab your saves and nuke the .ftba folder, which the FTB App uses to put all its stuff in.

Detailed workaround guide for Windows:
1. Go into your user folder (C:/Users/(yourusername)/) and open the .ftba folder. You might have to enable Hidden Items under the View tab.
2. Back up your saves, configs, etc. irreplaceable stuff from the "instances" sub-folder. The folder names will be strings of numbers and letters, but the art.png files in each one will tell you what's what.
3. Delete the whole .ftba folder.
4. Give it another go, reinstalling the packs in the app. Move your Saves folders from the backup to the fresh installations the app will generate.

Alternatively, you can delete the launcher_profiles.json and the malformed instance.jsons, which will cause the app to redownload things as new instances and keep the old installs where they are, that worked for me, but it's probably just better practice to grab what's important and Nuke It From Orbit.

**Comment by Rushmead** [comment]
Thanks for the details @cha0sbuster, do you have any information for us on how to re-create this issue? Are you installing the app to a specific location, could you also please provide us with the versions of the app you are using.

**Comment by cha0sbuster** [comment]
> Thanks for the details @cha0sbuster, do you have any information for us on how to re-create this issue? Are you installing the app to a specific location, could you also please provide us with the versions of the app you are using.

Welcome! Happy to help.

I'm not putting it anywhere specific, just the default location on Windows 10.

I don't have specific recreation steps, it was just kinda working one day and then not working the next. But a few details that may be relevant:

1. The app WAS outdated, part of troubleshooting involved updating it. I deleted the old installer, but the filename (from Chrome) was FTBA_windows-x64_202006121223-ac73c94902
2. While backing up saves, I had to clear some space on my C drive, so it may be related to that.
3. The app (and FTB:University) was running overnight; I had put my laptop to sleep so I could get right back to it the next day. The issue started after I then closed it later to allocate some more RAM as it was hitching; it just wouldn't start back up.

So any number/combination of those things could have contributed.

**Comment by Friggedjur** [comment]
Hello, i have the exact same problem as the above. I don't seem to find the folder/files u are talking about tho. Which of these folders should I remove?
![image](https://user-images.githubusercontent.com/73591256/97432955-0abf7e80-191d-11eb-8cc9-e556d8d94fae.png)

**Comment by Friggedjur** [comment]
@cha0sbuster @Rushmead @azChaz

**Comment by cha0sbuster** [comment]
You're in AppData/Roaming/FTBA, you just want C:/Users/(your username)/.ftba

Like this.
https://i.imgur.com/1hx5VwP.png

(This was a mistake I made too, don't sweat it.)

**Comment by Friggedjur** [comment]
Solved it, thank you @cha0sbuster

**Comment by MichaelHillcox** [comment]
This has very likely been fixed already. Please reopen if this is not the case
