### ISSUE TITLE
[Feature request]An "All" option when looking at the available modpacks. ... and other comments on the launcher

### ISSUE THREAD

**Issue by Michael-McKinley** [FTBTeam/FTB-App#308]
It is difficult to find modpacks that I know exist on the platform.

The "Home" page lists the modpacks I have installed, and 5 "Featured" packs. The name of the "Discover" option is misleading.  As this is a Modpack launcher, I expect Discover to be a search feature where I can "Discover" modpacks that are available, which is of course what the "Browse" option is for.

The "Browse" option offers filters for "Featured", "Top Installs", and "Top Plays". This is nice, but if a modpack I am looking for does not fit one of these categories, or I am not interested in any of the suggested options, then the ability to display "All" modpacks at say 15 packs per page, would be nice so I can actually "Browse" your selection.

Like many here, I am glad you are back but very frustrated with the new launcher. Besides this issue, it has others like new comments to old news posts, updates the date of the news post.  Case-in-point, the release of the new launcher news post currently shows a date/time stamp of 12 Oct 2020 ... or just 7 days ago.  The posting that announced you are expanding the team and states the launcher was released 8 days prior lists 13 August 2020 ... or two months earlier than the post announcing the release itself.  This makes trying to follow what is going on difficult and confusing.

Finally, news postings (and that is to say updates from the FTB Team to us "the users) are extremely slow and detached. I moved from the Technic Platform to the FTB Platform shortly after its initial launch long before the FTB-Twitch partnership because I appreciated your willingness to take a stand against people using mods without the author's permission and the openness of the communication and connection you seemed willing to have with your users.  The fact that you are still maintaining that integrity towards mod authors is great, but you could do with an improved user relations program.

**Comment by Gaz492** [comment]
Hi,

The discover page is there for people who would like to discover new packs and get a sense of what type of modpack it is. Often the modpacks displayed on the discover page will contain a video of a playthough/tutorial of what's in the modpack.
We are always open for suggestions regarding changes to the app so if you have any suggestions for different names for this page please let us know.

Regarding the browse all feature, this is something that we have planned however it does require some background work so it can be implemented without affecting the performance of the app and systems running the app. You can read more about this in issue #103 

The issue regarding the dates on the news page is a known issue and something that we are unable to fix at the moment as the issue is related to the software we use to post the news updates. We are hoping that a future update to the software will fix this issue but at the moment there is nothing we can do to resolve this.

I will forward your last comment to someone who can answer it in more detail.

Remember if you have any feature requests we have an issue template you can follow to request the feature, just make sure to search the issue tracker to make sure its not already been suggested.

**Comment by Quetzi** [comment]
Hey Michael, 

As Gaz has already said, we know that there are several improvements that need to be made to improve the user experience on the App. There are technical reasons behind why these haven't yet been improved, something that we have been working to change and hope to be able make significant progress on soon. I know it may seem like not too much is happening right now, but we have been setting up a significant change to the way we operate so that we are in a position to give the App the attention it deserves, along with that will come more communication and community driven activity. We have a busy few months ahead and core to that is continued App development and community relations.

**Comment by Michael-McKinley** [comment]
WOW! That was faster than I expected. Thank you so much for your time answering this. I appreciate it more than I can say. And look forward to seeing what is coming.

Michael McKinley
CompTIA A+, PROJECT+, SECURITY+
MS Network and Database Fundamentals
541-554-2760

Volunteer and Board of Directors Exotic Bird Rescue of Oregon

________________________________
