### ISSUE TITLE
[Bug (Windows)]

### ISSUE THREAD

**Issue by beverneus** [FTBTeam/FTB-App#387]
**Operating System:**
OS: Windows 10

**App Version:**
App: 202101031227-c13fc1b2e5-prototyping

**UI Version:**
UI: 85b019e3

**Log Files:**
https://pste.ch/zeqibaqula
** Debug Code: **
FTB-DBGGOMEPECUHI

**Describe the bug**
When I open the ftb app not all packs are available in the launcher and the bar underneath settings is stuck on loading. When I search a modpack I get an error message: "User is not registered".

**To Reproduce**
Steps to reproduce the behaviour:
I don't know

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/36573562/105045525-4b381f80-5a68-11eb-80e0-5c82de2cc869.png)
![image](https://user-images.githubusercontent.com/36573562/105045572-58eda500-5a68-11eb-9ff2-41b75a0e0af8.png)

**Comment by Chris5286** [comment]
I've got a similar if not the same issue. After several reboots and re-installs, I believe it has something to do with the MineTogether Discord connection as I don't recall having this issue with just the Minecraft account connection. Raised the issue with the MineTogether support and waiting for a confirmation of connection removal (since it seems we can't remove the connections ourselves on their site) to test it.

**Comment by gigabit101** [comment]
This issue should now be resolved, If the issue continues please do feel free to re-open the issue
