### ISSUE TITLE
Failed to Log In : Authentication Servers Down[Bug]: 

### ISSUE THREAD

**Issue by Saskia0000** [FTBTeam/FTB-App#501]
### What Operating System

Windows 10

### App Version

202203051730-9df8355f62-release

### UI Version

9df8355f62

### Debug Code

FTB-DBGALEKOHAWOK

### Describe the bug

(sry for bad english i am german) me and my friend started ftb revelation and my server on aternos then the error message came up:Failed to Log In : Authentication Servers Down. Then we tryed to login in again in the ftb app then the message comes up: something went wrong. failed to authenticate microsoft authentication...... but we have buy minecraft we have an microsoft konto and we already played minecraft and ftb a lot.

### Steps to reproduce

1go to ftb revelation start to load
2. click on the server you want to join(idk if this is on normal world too)
3.  see the error

and then we restart ftb app then the message came that we have to log in again and then the second message came

### Expected behaviour

i dont know what you mean with this question sry

### Information

- [X] I have provided as much information as possible

**Comment by the1xaks** [comment]
I was having the same problem all morning. It's working again.

I had to sign out of the FTB launcher, close it, reload it, and re-authenticate with Microsoft in order to get things working, but I can load into my server hosted world now

![image](https://user-images.githubusercontent.com/88561682/158634921-c4679944-88c3-45b1-a24d-05840495d133.png)

**Comment by MichaelHillcox** [comment]
Auth servers are back up so this should be sorted now
