### ISSUE TITLE
Wrong GPU 

### ISSUE THREAD

**Issue by totallyastick** [FTBTeam/FTB-App#549]
I am using a pc to play sky odyssey, and it's using my integrated GPU instead of my nvidia GPU, any fixes?

**Comment by CoryNB** [comment]
Add more ram, if it has 2 ram slots, go with the maximum ram it can handle for a single slot of ram for both of them.

**Comment by MichaelHillcox** [comment]
u what now?

**Comment by Raidobw2** [comment]
> ...with the Nvidia control panel you can select the GPU to run certain apps, like the Minecraft launcher if you prefer that. Open it and click "Manage 3D settings". Then click "Program settings" in the tabs at the right. Select the program you want to change the used graphics card for, such as [Java], then click the dropdown "preferred graphics processor" and choose your Nvidia GPU.

![image](https://user-images.githubusercontent.com/17010632/169901733-a247c5f9-47a2-4fd6-b19b-6292db080615.png)

Another option is disabling integrated graphics inside your computer's BIOS, at the start. You'll need to lookup your motherboard online in order to understand how to do that.

For AMD, configuration is done in the Radeon software instead, similarly to Nvidia.

**Comment by totallyastick** [comment]
I fixed it by changing my graphics settings in windows to high performance, thank you all for the suggestions though!
