### ISSUE TITLE
Missing essential log in information

### ISSUE THREAD

**Issue by Target244** [FTBTeam/FTB-App#897]
### What Operating System

Windows 11

### Debug Code

 FTB-DBGEYUBUSOJIR

### Describe the bug

I am try to login to FTB app

### Steps to reproduce

try to log into  FTB app with a Microsoft login

### Expected behaviour

will not accept login

### Screenshots

![image](https://user-images.githubusercontent.com/131054527/232617893-e894aaf1-cb89-4866-9669-78dbc37b73b4.png)

**Comment by Target244** [comment]
![image](https://user-images.githubusercontent.com/131054527/232625852-27960574-4785-4c33-8c73-874d2bb308e7.png)
I know getting this error after turning of AV and FW .

**Comment by ltzLucas** [comment]
I have the same problem

**Comment by CosmicPhoenixgh** [comment]
I know how to fix this: 

You need to switch emails (preferably to gmail rather than outlook) when you login.

Or you need to migrate your mojang account to microsoft.

You can also, if you have some money, buy minecraft from the microsoft store without needing to migrate your mojang account since you will be required to login with a microsoft account.

Hope this helps :)

**Comment by CosmicPhoenixgh** [comment]
> [Target244](/Target244)

I know how to fix this: 

You need to switch emails (preferably to gmail rather than outlook) when you login.

Or you need to migrate your mojang account to microsoft.

You can also, if you have some money, buy minecraft from the microsoft store without needing to migrate your mojang account since you will be required to login with a microsoft account.

Hope this helps :)
