### ISSUE TITLE
[Bug] Mac launcher deletes all data when it updates itself

### ISSUE THREAD

**Issue by dgelessus** [FTBTeam/FTB-App#90]
**Operating System:**
OS: macOS 10.14.6

**Installer Version:**
Installer: I don't know where to find this? I have the launcher installed already, and the Mac version doesn't even have an installer (it comes on a disk image).

**App Version:**
App: 1.0.6

**UI Version:**
UI: c84af85886609817d5af5a51677f6f0d583661f5

**Log Files:**
https://pste.ch/ixanujakot

**Describe the bug**
When the Mac launcher updates itself, it deletes all instances.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have an old version of the launcher installed on Mac
2. Open the launcher
3. Have the launcher update itself

**Expected behaviour**
My instances from the previous version should still be here.

**Additional context**
I'm not able to test/reproduce this properly, as there's no way to download older versions of the launcher (I haven't kept the old disk image). Even if I still had an older launcher version around, it would automatically update itself as soon as I run it, so I wouldn't have any way to install a modpack first for testing.

**Comment by prple** [comment]
This is due to the fact that modpack instances are stored inside the FTBApp.app package. 
Having a way to install them out of the package would greatly help to fix this bug.

**Comment by s0ph0s-2** [comment]
Would it be welcome for me to dive into the code and try to figure out how to put stuff in `~/Library/Application Support/Feed The Beast` instead? That's where Mac apps are supposed to put this sort of data, and it would keep this problem from happening in the future.

**Comment by s0ph0s-2** [comment]
As a work-around, if you'd like to keep your data between updates, here's what I've figured out works. Some of these folders/files might not be necessary, but it'll keep your data from randomly being deleted.
1. Right-click the FTB app before the update and select Show Package Contents
2. Copy all of these files/folders out of the app:
- `Contents/Resources/app/instances/`
- `Contents/Resources/app/bin/launcher_profiles.json`
- `Contents/Resources/app/bin/launcher_settings.json`
- `Contents/Resources/app/bin/settings.json`
- `Contents/Resources/app/bin/versions/`
3. Let the app update and delete your data
4. Copy all of the files you backed up in step 2 back into the app in the same places

**Comment by mworzala** [comment]
@s0ph0s-2 its not in this repository, it would be in the CreeperHost side, and I can save you the trouble of finding it. It is because the system property `user.dir` is the directory containing the jar file, which happens to be inside the app package (`FTBApp.app/Resources/app`).

`user.dir` is used [here](https://github.com/CreeperHost/modpacklauncher/blob/81b9238150c104ed23a8f0d44b1a9a3389ed2fb8/src/main/java/net/creeperhost/creeperlauncher/Constants.java#L10) to define the data directory, which is used to define the instance directory [here](https://github.com/CreeperHost/modpacklauncher/blob/81b9238150c104ed23a8f0d44b1a9a3389ed2fb8/src/main/java/net/creeperhost/creeperlauncher/Constants.java#L39). The instance directory is used when installing the pack to determine the directory for the instance data [here](https://github.com/CreeperHost/modpacklauncher/blob/81b9238150c104ed23a8f0d44b1a9a3389ed2fb8/src/main/java/net/creeperhost/creeperlauncher/pack/LocalInstance.java#L68).

Notably the path comes from `Settings.settings.getOrDefault("instanceDir", Constants.INSTANCES_FOLDER_LOC)` which means that if you set the `instanceDir` field in the settings json it will change the install location. The problem with that is that the settings json file is also stored in the app package (seen [here](https://github.com/CreeperHost/modpacklauncher/blob/81b9238150c104ed23a8f0d44b1a9a3389ed2fb8/src/main/java/net/creeperhost/creeperlauncher/Settings.java#L26), `BIN_LOCATION` is defined [here](https://github.com/CreeperHost/modpacklauncher/blob/81b9238150c104ed23a8f0d44b1a9a3389ed2fb8/src/main/java/net/creeperhost/creeperlauncher/Constants.java#L33)) so it will also be reset.

This is a fairly easy change, and obviously you can submit a pull request for it, however CreeperHost [has not been the most positive about external contribution.](https://github.com/CreeperHost/modpacklauncher/issues/1)

**Comment by Jake-E** [comment]
Instances are now stored outside of the .app, this should no longer be an issue.
