### ISSUE TITLE
Profile Validation Failed

### ISSUE THREAD

**Issue by NarcolepticBurrito** [FTBTeam/FTB-App#916]
### What Operating System

Windows 11

### Debug Code

FTB-DBGRIVAMOJIVE

### Describe the bug

Everytime I try to start any modpack, I get something saying Profile Validation Failed. I've been trying to get help for 2 days now. 

### Steps to reproduce

1. Open FTB
2. Try to launch any game
3. Get the same error?

### Expected behaviour

Should open the modpack I'm clicking

**Comment by 999mamacita** [comment]
I have been having this very same problem. I have tried to reach out in the Discord chat as the error message says to do, but no one will acknowledge my requests. Once someone asked me to run the debugger, which I did, but no one has replied since, and I've made the request multiple times , always including the debugger code in subsequent messages. It's really frustrating because my family wants to play together, we've been through a lot this year, and this error is only allowing me to play offline. I really hope someone can help out with this.

Fresh debugger result: FTB-DBGILAXUVUWAL

![Minecraft - FTB - profile validation issue 01](https://github.com/FTBTeam/FTB-App/assets/134969834/c0478037-bd20-45ee-ab44-5635da6d4610)

Thank you all for any help you can provide, it is greatly appreciated.

**Comment by Raidobw2** [comment]
Thanks for the reports, I've replied to 999mamacita on the FTB Discord.

@NarcolepticBurrito can you try these steps, if the issue still persists to today?

1. Close the FTB App and exit Overwolf
2. Paste `%localappdata%\.ftba` in the address bar of the File Explorer and press Enter to reach the folder
3. Delete the `profiles.json` file you should see
4. Start the FTB App and try to login, play a modpack

Please let me know if that worked or not, thank you

You can also log in to the Minecraft site https://www.minecraft.net/ and verify that you own Minecraft on that account. Sometimes people will enter the wrong email by accident and I'm aware the FTB App doesn't specifically warn users about this! I'll suggest something to the app devs

**Comment by 999mamacita** [comment]
YOU ARE MY HERO, this WORKED perfectly!!!! I have reposted the solution in the chat for others having the same issue as well. YOU TOTALLY SAVED THE DAY thank you SO much!!!!



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
