### ISSUE TITLE
[MacOS] A secondary "child" application shows as open in Dock instead of primary parent application

### ISSUE THREAD

**Issue by Next-Door-Tech** [FTBTeam/FTB-App#921]
### What Operating System

MacOS (Latest)

### Debug Code

FTB-DBGWUBEKABOWU

### Describe the bug

On MacOS, when the app is opened an internally-packaged application appears as a second, separate active app icon in the dock, while the primary application dock icon appears to be quit.

### Steps to reproduce

Please see this [screen capture with voiceover](https://youtu.be/wYgkAtViSTQ) which I think explains the issue much better than I can in text: https://youtu.be/wYgkAtViSTQ

1. On macOS, install the latest FTB App to the Applications folder as usual
2. Drag FTB App from Applications folder to Dock (this is the "primary" dock icon)
3. Open FTB App using Dock icon
4. A second dock icon appears which does not 

### Expected behaviour

No second app icon should appear in the dock, and main dock icon should appear as active while the app is still open

### Screenshots

https://youtu.be/wYgkAtViSTQ

**Comment by CoryNB** [comment]
multi threaded jobs in minecraft are hard because it wasn't designed for that.

**Comment by Next-Door-Tech** [comment]
> multi threaded jobs in minecraft are hard because it wasn't designed for that.

To clarify, this is an issue with the FTB launcher frontend, nothing to do with Minecraft itself here.

**Comment by MichaelHillcox** [comment]
Ah! Thanks for the awesome video showing what's going wrong. This is the correct behaviour but definitely not ideal. We use something called `Install4j` which handles the installation of the app on macos and linux. Due to the way this system works, the first FTB App you clicked is the "Starter" which sets a bunch of stuff up, ensures you have Java, etc etc, then if all that works, it closes and starts the actual FTB App up. 

I'd love to solve this for you but... It's kinda just how that system works. I'll look to see if I can fix it by forcing both of the apps have the exact same name as it looks like they we're different but I can't confirm if that will fix it.

It's been an internal goal for a while now to get rid of Install4J but as it's currently working... it's kinda gone to the bottom of the list.
