### ISSUE TITLE
RAM Settings

### ISSUE THREAD

**Issue by Slowpoke101** [FTBTeam/FTB-App#94]
We have an issue where the minimum amount of RAM (4gig) is not quite enough to smoothly launch all packs. Suggesting a change where if a person has more than 12gig RAM, then instead of setting the profile to the minimum ram, it sets it to the recommended instead.

**Comment by CH-Paul-T** [comment]
Likely be more like...

if(totalsysmem > recommended*1.8)? If that's fine?

So that'd mean if the recommended memory was 6gb

It'd switch to recommended instead of minimum as default on any system with more than 10.8gb ram

That way it'd at least scale as recommendations go up and down, gotta remember, the way Minecraft is going you'll need 64gb to launch vanilla by 2022.

**Comment by Lupoid** [comment]
With this, could the slider also be reviewed... not a big fan when you want something to increment a bit more digitally. Who would want to spend a good few minutes fiddling with everything between 5.98-6.04G for it to then push an incorrect value through to the game?

**Comment by Jake-E** [comment]
This change was made 7 months ago.
