### ISSUE TITLE
Failed to prepare instance because of java.nio.file.accessdeniedexception

### ISSUE THREAD

**Issue by Anarph** [FTBTeam/FTB-App#974]
### What Operating System

MacOS (Latest)

### Debug Code

Can't find the debug code with the ftb-debug for macos

### Describe the bug

I can't relaunch a modpack (Seaopolis 2) even with a fresh install

### Steps to reproduce

Hello, 
I was playing to Seaopolis 2 yesterday. Everything was fine. I exit the game normally. Today, when I launch the modpack, it crashes at Validate Java Runtime.
What I already did : 
- Delete the instance and I reinstall modpack : First, it made a fatal error to reinstall the modpack.
- Try another modpack (seaopolis 1 and stoneblock) : works fine
- Remove the FTBapp and the .ftbapp folder and reinstall FTBapp. I can reinstall Seaopolis 2 but the problem of Java Runtime reappears with a fresh install
- Install Seaopolis 2 with curseforge launcher. I can launch the game but the save is not working

Any idea to finish my questbook ?

<img width="922" alt="Capture d’écran 2023-10-07 à 11 34 30" src="https://github.com/FTBTeam/FTB-App/assets/9317898/3c7e84cf-0d76-4531-8cd0-c2f476a6c22e">

Thank you for this and for your work.

### Expected behaviour

I just want to launch the modpack and finish this quest book :)

**Comment by atealein** [comment]
This is the same issue that is described in https://github.com/FTBTeam/FTB-App/issues/972 ; see the comment for a workaround ( https://github.com/FTBTeam/FTB-App/issues/972#issuecomment-1751576152 ) basically you need to go in your instance settings and point to the older java version and not the one that was just installed. Unfortunately, you have removed your FTB app so that means you don't have the old java versions so you might have to install manually.

**Comment by Anarph** [comment]
Thank you @atealein. We were in the same situation.
FTBapp team made changes and it occured trouble with Java. Just launch FTB to test you're solution and a hot fix was made.
My world is back !

**Comment by Anarph** [comment]
I close the subject
